salus:
  presence-monitor:
    exportPeriod: 5
  worker:
    prefix: /workAllocations/PRESENCE_MONITOR
spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: presence-monitor-${random.value}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages:
                com.rackspace.salus.telemetry.messaging
  jackson:
    mapper:
      default-view-inclusion: true
  application:
    name: salus-telemetry-presence-monitor
management:
  metrics:
    export:
      influx:
        uri: ${salus.metrics.influx.uri:http://localhost:8086}
        db: salus
        enabled: ${salus.metrics.influx.enabled:false}      