presence-monitor:
  kafka:
    bootstrap-servers: localhost:9092
    group-id: presence.monitor
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    auto-offset-reset: latest
  kafka-topics:
    LOG:
      telemetry.logs.json
    METRIC:
      telemetry.metrics.json
    EVENT:
      telemetry.events.json
    RESOURCE:
      telemetry.resources.json
  exportPeriod:
    5
  resourceManagerUrl:
    http://localhost:8082/auth/sse
etcd:
  url: http://localhost:2479
worker:
  prefix:
    /workAllocations/PRESENCE_MONITOR
spring:
  main:
    web-environment:
      false
