presence-monitor:
  kafka-topics:
    LOG:
      telemetry.logs.json
    METRIC:
      telemetry.metrics.json
    EVENT:
      telemetry.events.json
    RESOURCE:
      telemetry.resources.json
  exportPeriod:
    5
  resourceManagerUrl:
    http://localhost:8082/auth/sse
etcd:
  url: http://localhost:2479
worker:
  prefix:
    /workAllocations/PRESENCE_MONITOR
spring:
  application:
    name: presence.monitor
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: presence.monitor
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages:
                com.rackspace.salus.telemetry.messaging
  main:
    web-environment:
      false

---

spring:
  profiles: test
  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers}
  
presence-monitor:
  exportPeriod:
    1
  resourceManagerUrl:
    http://localhost/getResources
