server:
  port: 8083
logging:
  level:
    com.rackspace.salus: debug
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
services:
  resource-management-url: http://localhost:8085