presence-monitor:
  kafka-topics:
    LOG:
      telemetry.logs.json
    METRIC:
      telemetry.metrics.json
  exportPeriodInSeconds:
    5
etcd:
  url: http://localhost:2479
worker:
  prefix:
    /workAllocations/PRESENCE_MONITOR
