salus:
  etcd:
    url: http://localhost:2479
  services:
    resource-management-url: http://localhost:8085
server:
  port: 8083
logging:
  level:
    com.rackspace.salus: debug
spring:
  kafka:
    listener:
      # this will allow for us to start consumer of a particular topic before the producer
      missing-topics-fatal: false
